import Head from 'next/head'
import Image from 'next/image'

import Menu from '../components/Menu'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Livro & Café</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/coffee-break.png" />
      </Head>
			<Menu />
      <main className={styles.main}>
        
     <div className={styles.esta}><p><img src="/images/cafe e livro.jpg" height={720} 
    width={1347}/></p></div>
        <div className={styles.textotitulo}><h1>Livro & Café</h1></div>
        <div className={styles.textosec}>Abra um livro e pegue um café. 
        E seja bem vindo</div>
        
      </main>

      <footer className={styles.footer}>
		  <a href="https://replit.com/@SamaraFernandes" target="_blank">   © 2022 - SamaraFernandes.</a>
        
      </footer>
    </div>
  )
}
