import Head from 'next/head'
import Image from 'next/image'


import Menu from '../components/Menu'
import styles from '../styles/Home.module.css'

export default function Contatos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Livro e café</title>
        <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="images/coffee-break.png" />
      </Head>
			<Menu />
      <main className={styles.main}>
        <h3 className={styles.title}>
          Faça seu login em nossa página.       
				</h3>
        <form >
    <div className="formulario-container">
    <div>
        <label for="nome">Nome Completo: <br/></label>
        <input type="text" id="nome" />
    </div>
    
    <div>
        <label for="email">E-mail: <br/></label>
        <input type="email" id="email" />
    </div>
    <div>
        <label for="senha">Senha: <br/></label>
        <input type="password" id="senha" />
    </div>
    <br/>
    <button type="submit">Enviar</button>
    
    </div>
</form>
      </main>

      <footer className={styles.footer}>
		  <a href="https://replit.com/@SamaraFernandes" target="_blank">   © 2022 - SamaraFernandes.</a>
        
      </footer>
    </div>
  )
}